name: bert
channels:
- conda-forge
- defaults
dependencies:
- beautifulsoup4=4.6.0
- nltk=3.4.1
- numpy=1.16.1
- pandas=0.24.2
- pip=19.1.1
- python=3.6
- scikit-learn=0.21.1
- scipy=1.3.0
- tensorflow=1.13.2
- pip:
  - tqdm==4.32.2
