name: bert
channels:
- conda-forge
- defaults
dependencies:
- numpy=1.16.1
- pandas=0.24.2
- pip=19.1.1
- python=3.6
- scikit-learn=0.21.1
- scipy=1.3.0
- ipykernel=5.1.1
- matplotlib=3.1.1
- seaborn=0.9.0
- jupyter=1.0.0
- pip:
  - tensorflow==1.13.1
